### ISSUE TITLE
imagefluency package is not working 

### ISSUE THREAD

**Issue by bssengul** [stm/rquantae#8] opened 2023-10-20 12:50 UTC
Hello everyone,

I downloaded imagefluency package to analyze my images in Rstudio. I wrote code, added my images to example_images file. But code is not working. I dont even get any error message from code. Can you help me about this situation?

library(imagefluency)

# Get complexity, contrast, simplicity and self similarity values of multiple images in a given folder (all images should be loaded in the "example_images" folder)

 imglist <- list("high_1.jpg", "high_2.jpg.jpg", "high_3.jpg", "high_4.jpg.jpg", "high_5.jpg.jpg", "high_6.jpg.jpg")

for (i in imglist) {

	i <- img_read(system.file("example_images", i, package = "imagefluency"))

	print(data.frame(img_complexity(i),img_contrast(i), mean(rgb2gray(i)), img_self_similarity(i)))

**Comment by stm** [comment] 2023-10-20 20:12
The problem with your code is that `system.file()` is intended to provide file paths and names of files that are part of an R package. Hence, in your command `i <- img_read(system.file("example_images", i, package = "imagefluency"))` you are telling R to search for the image `high_1.jpg` (if `i = 1`) in the subdirectory `example_images` of the {imagefluency} package.

If you want to analyze images stored in a folder on your system, the following code should work.

```r
library(imagefluency)

# make sure that the folder `example_images` is a subfolder of your current working directory
# to check the current working directory, use `getwd()`
# to change the current working directory, use `setwd()`
dir.exists("example_images/")

# define image list
imglist <- c("high_1.jpg", "high_2.jpg", "high_3.jpg", "high_4.jpg", "high_5.jpg", "high_6.jpg")

for (i in imglist) {
  # read image (file path is constructed with `paste0()`)
  img <- img_read(paste0("example_images/", i))
  
  # calculate and print scores
  print(data.frame(
    img_complexity(img),
    img_contrast(img),
    mean(rgb2gray(img)),
    img_self_similarity(img))
  )
}
```

Alternatively, instead of constructing the file paths manually, a more elegant way would be to let R search for images in the `example_images` folder.
```r
# here, we only search for images with the extension .jpg
imglist <- list.files("example_images", pattern = '*.jpg$', full.names = TRUE)

for (i in imglist) {
  # read image
  img <- img_read(i)
  
  # calculate and print scores
  print(data.frame(
    img_complexity(img),
    img_contrast(img),
    mean(rgb2gray(img)),
    img_self_similarity(img))
  )
}
```

---

If your goal is to **store** the **results** of all images in a data frame, then the following code can be used:
```r
imglist <- list.files("example_images", pattern = '*.jpg$', full.names = TRUE)

# data frame to store results 
results <- data.frame(filename = basename(imglist),
                      complexity = NA, contrast = NA,
                      mean = NA, selfsimilarity = NA)

# loop
for(i in seq_along(imglist)){
  # print loop info
  print(paste('** Estimating scores for image',i,'**'))
  
  # 1. read image into R
  img <- img_read(imglist[i])
  
  # 2. estimate scores and store the results
  results$complexity[i] <- img_complexity(img)
  results$contrast[i] <- img_contrast(img)
  results$mean[i] <- mean(rgb2gray(img))
  results$selfsimilarity[i] <- img_self_similarity(img)
}

# print data frame
print(results)
```

**Comment by bssengul** [comment] 2023-10-22 18:10
Hello, thank you for your detailed answer. example_images folder is actually in the imagefluency folder in my computer. It's also in the R folder. I added my images to example_images folder but the code still did not work.

**Comment by stm** [comment] 2023-10-23 15:42
It'd be very helpful to have more details about the error message (and to have a [minimal reproducible example](https://www.tidyverse.org/help/#reprex). However, it does not seem like there's actually a bug in the package, but more like you would need help with your R code in general.

If you just want to calculate imagefluency scores for a few images, the shiny app might be a suitable alternative. You can run the app either by executing the following code or by visiting [shinyapps.io](https://mayer.shinyapps.io/imagefluency/).

```r
imagefluency::run_imagefluency() 
``` 
As I saw that you posted the same question on [community.rstudio.com](https://community.rstudio.com/t/imagefluency-package-is-not-working/175809), I'll close this issue here.

**Closed as completed by stm** 2023-10-23 15:42 UTC
